### ISSUE TITLE
Update Google Anayltics ID in configuration

### ISSUE THREAD

**Issue by kshitij10496** [sangeet259/hugo-blog#1]
Hey @sangeet259 

I'm glad to see that you have got the blog up and running! 😃 
Also, thanks a lot for citing my post here. ❤️ 

However, I came to notice that there is a small issue of reusing my Google Analytics ID in this blog.
As a result of this, I'm getting a lot of traffic report on my Google Analytics dashboard from your blog.

Thus, it'd be great if you create a new analytics ID and update the `googleAnalytics` field in the configuration file ASAP! In case you do not want to add site analytics right now, removing the field altogether would work as well. 😄 

Cheers!

**Comment by sangeet259** [comment]
Damn ! I guess I missed this one.
I will update this asap.
Thanks for opening this issue. :)

**Comment by sangeet259** [comment]
Fixed by commit 6b20a87
